language: r

cache: packages

r_binary_packages:
    - devtools
    - oro.nifti
    - testthat
    - roxygen2

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

warnings_are_errors: false
